apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: ebc38238181f40ed37ad03a927c3c1975423c9511b40000363163c972956e04e
    cni.projectcalico.org/podIP: 10.42.2.200/32
    cni.projectcalico.org/podIPs: 10.42.2.200/32
    kubernetes.io/psp: global-unrestricted-psp
  creationTimestamp: "2022-02-12T15:59:24Z"
  labels:
    run: debug-shell
  name: debug-shell
  namespace: default
  resourceVersion: "1494143"
  uid: 953327ad-3fd7-4921-a532-a45ab4031008
spec:
  containers:
  - args:
    - sh
    image: alpine
    imagePullPolicy: Always
    name: debug-shell
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-htgph
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: prod-geowallet-node-02
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config-vol
    configMap:
      name: log-config
      items:
        - key: log_level
          path: log_level
  - name: kube-api-access-htgph
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-12T15:59:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-12T15:59:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-12T15:59:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-12T15:59:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://44e1ac623fd546bf0a6eed7d9a4f82da8eea9648d0bd6ac670ece1b8062b9d52
    image: docker.io/library/alpine:latest
    imageID: docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
    lastState: {}
    name: debug-shell
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-02-12T15:59:25Z"
  hostIP: 141.94.131.200
  phase: Running
  podIP: 10.42.2.200
  podIPs:
  - ip: 10.42.2.200
  qosClass: BestEffort
  startTime: "2022-02-12T15:59:24Z"
