apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: ebc38238181f40ed37ad03a927c3c1975423c9511b40000363163c972956e04e
    cni.projectcalico.org/podIP: 10.42.2.200/32
    cni.projectcalico.org/podIPs: 10.42.2.200/32
    kubernetes.io/psp: global-unrestricted-psp
  labels:
    run: debug-shell
  name: debug-shell
  namespace: default
spec:
  containers:
  - args:
    - sh
    image: alpine
    imagePullPolicy: Always
    name: debug-shell
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts: []
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: prod-geowallet-node-02
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      items:
      - key: log_level
        path: log_level
      name: log-config
    name: config-vol
